name: Publish NPM image
description: Publish NPM packages

inputs:
  project:
    description: 'Directory path of the published npm package'
    required: true
  before_hook_cmd:
    description: 'Hook command to run before publishing'
    required: false
  NPM_AUTH_TOKEN:
    description: 'NPM auth token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm ci
      shell: bash
    - run: "${{ input.before_hook_cmd }}"
      shell: bash
    - run: npm publish
      working-directory: ${{ inputs.project }}
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NPM_TOKEN }}
