name: Publish Docker image
description: Publish a docker image

inputs:
  project:
    description: 'Project name and name path of the project where the docker image should be built'
    required: true
  DOCKER_USERNAME:
    description: 'Docker username'
    required: true
  DOCKER_PASSWORD:
    description: 'Docker password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ inputs.DOCKER_USERNAME }}
        password: ${{ inputs.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ${{ inputs.project }}
        file: ${{ inputs.project }}/Dockerfile
        push: true
        tags: ${{ inputs.DOCKER_USERNAME }}/viteo-${{ inputs.project }}:latest
