apiVersion: v1
kind: Service
metadata:
  name: basic-stream-service
  namespace: basic-stream-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app.name: basic-stream-service
  type: ClusterIP
