deployment:
  test:
    enabled: false

controller:
  proxy:
    nameOverride: kong-gateway-proxy

  enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true

    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

gateway:
  enabled: true
  deployment:
    kong:
      enabled: true
    userDefinedVolumes:
     - name: "grpc-proto-shared-pvc"
       hostPath:
         path: "/usr/include/grpc-proto-shared/services"
    userDefinedVolumeMounts:
     - name: "grpc-proto-shared-pvc"
       mountPath: "/usr/include/"

  admin:
    enabled: true
    type: ClusterIP
    clusterIP: None

  ingressController:
    enabled: false

  env:
    role: traditional
    database: "off"
