deployment:
  test:
    enabled: false

controller:
  proxy:
    nameOverride: kong-gateway-proxy

  enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true

    gatewayDiscovery:
      enabled: true
      generateAdminApiService: true

gateway:
  enabled: true
  deployment:
    kong:
      enabled: true
    # TODO: I did 2 volumes because kong grpc-gateway import other proto files from root folder of the proto path
    userDefinedVolumes:
     - name: "grpc-proto-shared-pvc"
       hostPath:
         path: "/home/theo/GITHUB/viteo-vod-platform/grpc-proto-shared/services"
     - name: "grpc-proto-shared-pvc-google"
       hostPath:
         path: "/home/theo/GITHUB/viteo-vod-platform/grpc-proto-shared/services/google"
    userDefinedVolumeMounts:
     - name: "grpc-proto-shared-pvc"
       mountPath: "/mnt/protobufs"
     - name: "grpc-proto-shared-pvc-google"
       mountPath: "/usr/include/google"

  admin:
    enabled: true
    type: ClusterIP
    clusterIP: None

  ingressController:
    enabled: false

  env:
    role: traditional
    database: "off"
