apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kong
  source:
    path: kong/infra/helm
    repoURL: https://github.com/theocerutti/viteo-vod-platform.git
    targetRevision: master
    helm:
      valueFiles:
        - values-dev.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
