name: Publish Docker image

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry:
          - context: basic-stream-service
            dockerfile: basic-stream-service/Dockerfile
            name: basic-stream-service
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ matrix.registry.context }}
          file: ${{ matrix.registry.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/viteo-${{ matrix.registry.name }}:latest
